# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sid Masih
tagline:          '2nd year CS Student from Berkeley'
description:      '2nd year CS Student from Berkeley EECS'
url:              http://sidmasih.github.io

author:
  name:           'Sid Masih'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/SidMasih
