# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sid Masih
tagline:          '2nd year CS Student from Berkeley'
description:      'Please take a look at my work!'
url:              http://sidmasih.github.io

author:
  name:           'Sid Masih'

paginate:         5

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/SidMasih

footer-links:
  email: sid.masih@gmail.com
  facebook: /sid.masih.3
  linkedin: /sid-masih-65b54382
